# Generated by Django 3.1.2 on 2020-10-23 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(max_length=150, null=True)),
                ('Day', models.CharField(max_length=150, null=True)),
                ('Interval', models.CharField(max_length=150, null=True)),
                ('Quantity', models.CharField(max_length=150, null=True)),
            ],
        ),
    ]
