# Generated by Django 3.1.2 on 2020-10-26 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bates_Energy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observation',
            old_name='Day',
            new_name='month',
        ),
        migrations.AlterField(
            model_name='observation',
            name='Quantity',
            field=models.FloatField(null=True),
        ),
    ]
