# Generated by Django 3.1.2 on 2020-10-30 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bates_Energy', '0005_auto_20201027_0001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='observation',
            options={'ordering': ['-Day']},
        ),
        migrations.RemoveField(
            model_name='observation',
            name='Interval',
        ),
        migrations.AlterField(
            model_name='observation',
            name='Day',
            field=models.DateTimeField(null=True),
        ),
    ]
