# Generated by Django 3.1.2 on 2020-10-30 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bates_Energy', '0006_auto_20201030_0040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='observation',
            options={},
        ),
        migrations.RemoveField(
            model_name='observation',
            name='Day',
        ),
        migrations.AddField(
            model_name='observation',
            name='Time',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
