# Generated by Django 3.1.2 on 2020-11-14 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bates_Energy', '0008_auto_20201111_0221'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='observation',
            options={'ordering': ['date_time']},
        ),
        migrations.RenameField(
            model_name='observation',
            old_name='Time',
            new_name='date_time',
        ),
        migrations.RenameField(
            model_name='observation',
            old_name='Quantity',
            new_name='quantity',
        ),
    ]
