# Generated by Django 3.1.2 on 2020-11-14 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bates_Energy', '0009_auto_20201114_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='string_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
