# Generated by Django 3.1.2 on 2020-11-17 19:46

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bates_Energy', '0010_observation_string_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/media/photos'), upload_to='')),
            ],
        ),
    ]
